-- Sky's house: initial Supabase schema
-- Run this once in Supabase SQL Editor after the project is created.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,0),
  compare_at_price bigint,
  unit text not null default 'kg',
  category text not null default 'Sản phẩm khác',
  description text not null default '',
  image_url text not null default '',
  in_stock boolean not null default true,
  visible boolean not null default true,
  best_seller boolean not null default false,
  signature boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep existing projects compatible when this schema is re-run.
alter table public.products
  add column if not exists best_seller boolean not null default false,
  add column if not exists signature boolean not null default false,
  add column if not exists compare_at_price bigint;

create table if not exists public.site_settings (
  id bigint primary key default 1 check (id = 1),
  shop_name text not null default 'Sky''s house',
  owner_name text not null default 'Thiên-Milo',
  phone text not null default '0786646634',
  zalo_url text not null default 'https://zalo.me/0786646634',
  facebook_url text not null default 'https://www.facebook.com/vishiaonlysky',
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id) values (1)
on conflict (id) do nothing;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  customer_note text not null default '',
  items jsonb not null default '[]'::jsonb,
  subtotal_known bigint not null default 0 check (subtotal_known >= 0),
  has_contact_price boolean not null default false,
  shipping_fee bigint not null default 0 check (shipping_fee >= 0),
  final_total bigint check (final_total is null or final_total >= 0),
  admin_note text not null default '',
  status text not null default 'new' check (status in ('new','confirmed','shipping','completed','cancelled')),
  source text not null default 'zalo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders
  add column if not exists shipping_fee bigint not null default 0 check (shipping_fee >= 0),
  add column if not exists final_total bigint check (final_total is null or final_total >= 0),
  add column if not exists admin_note text not null default '';

create index if not exists orders_status_created_at_idx on public.orders (status, created_at desc);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

alter table public.products enable row level security;
alter table public.site_settings enable row level security;
alter table public.orders enable row level security;

-- Public storefront can only read visible products.
drop policy if exists "public read visible products" on public.products;
create policy "public read visible products"
on public.products for select
to anon, authenticated
using (visible = true or auth.role() = 'authenticated');

-- Any authenticated Supabase user is treated as an admin for this private shop.
-- If more admins are added later, replace these with a dedicated role table.
drop policy if exists "authenticated insert products" on public.products;
create policy "authenticated insert products"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "authenticated update products" on public.products;
create policy "authenticated update products"
on public.products for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete products" on public.products;
create policy "authenticated delete products"
on public.products for delete
to authenticated
using (true);

drop policy if exists "public read site settings" on public.site_settings;
create policy "public read site settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "authenticated update site settings" on public.site_settings;
create policy "authenticated update site settings"
on public.site_settings for update
to authenticated
using (true)
with check (true);

-- Storefront may create a new order, but only authenticated admin sessions may read/update orders.
drop policy if exists "public insert new orders" on public.orders;
create policy "public insert new orders"
on public.orders for insert
to anon, authenticated
with check (status = 'new');

drop policy if exists "authenticated read orders" on public.orders;
create policy "authenticated read orders"
on public.orders for select
to authenticated
using (true);

drop policy if exists "authenticated update orders" on public.orders;
create policy "authenticated update orders"
on public.orders for update
to authenticated
using (true)
with check (true);

grant insert on public.orders to anon, authenticated;
grant select, update on public.orders to authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;

-- Product image bucket.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images"
on storage.objects for select
to public
using (bucket_id = 'product-images');

drop policy if exists "authenticated upload product images" on storage.objects;
create policy "authenticated upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images');

drop policy if exists "authenticated update product images" on storage.objects;
create policy "authenticated update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

drop policy if exists "authenticated delete product images" on storage.objects;
create policy "authenticated delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images');
