create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  customer_note text not null default '',
  items jsonb not null default '[]'::jsonb,
  subtotal_known bigint not null default 0 check (subtotal_known >= 0),
  has_contact_price boolean not null default false,
  status text not null default 'new' check (status in ('new','confirmed','shipping','completed','cancelled')),
  source text not null default 'zalo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_status_created_at_idx on public.orders (status, created_at desc);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

alter table public.orders enable row level security;

drop policy if exists "public insert new orders" on public.orders;
create policy "public insert new orders"
on public.orders for insert
to anon, authenticated
with check (status = 'new');

drop policy if exists "authenticated read orders" on public.orders;
create policy "authenticated read orders"
on public.orders for select
to authenticated
using (true);

drop policy if exists "authenticated update orders" on public.orders;
create policy "authenticated update orders"
on public.orders for update
to authenticated
using (true)
with check (true);

grant insert on public.orders to anon, authenticated;
grant select, update on public.orders to authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;
